on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish to Cloudflare Pages
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 3f28d3a5c9a4bdc4a451bb2ce2ba89be
          projectName: l-fabon
          directory: dist/client
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
